#!/usr/bin/env bash
uair-check start
niri msg action focus-workspace "@noteWorkspace@"
uairctl jump med-prep
uairzen ': start your day off right by taking control of your mind 🧘 to enable intentional work 🌅' &
