loop_on_end = true

[defaults]
format = "{name}\n#{time}\n"
paused_state_text = "paused"
resumed_state_text = "resumed"

[[sessions]]
id = "work"
name = "!WORK!"
duration = "25m"
time_format = "%M:%S"
autostart = true
command = "notify-send 'Work Done!' & ghostty -e uairfiglet --title uairfiglet'"

[[sessions]]
id = "rest"
name = "~rest~"
duration = "5m"
time_format = "%M:%S"
autostart = true
command = "notify-send 'Rest Done!' & hyprctl dispatch closewindow 'title:uairfiglet'"

