loop_on_end = true

[defaults]
format = "{time}\n"
paused_state_text = "paused"
resumed_state_text = "resumed"

[[sessions]]
id = "work"
name = "!WORK!"
duration = "25m"
time_format = "%M:%S"
command = "notify-send 'Work Done!' & hyprctl dispatch exec '[pin; float; nofocus; center; size 500 150] alacritty --class uairctl --title rest -e uairtozero'"

[[sessions]]
id = "rest"
name = "~rest~"
duration = "5m"
time_format = "%M:%S"
autostart = true
command = "notify-send 'Rest Done!'"

