{
  NIXOS_OZONE_WL = "1";
  ELECTRON_OZONE_PLATFORM_HINT = "wayland";
  XDG_SESSION_TYPE = "wayland";
  SDL_VIDEODRIVER = "wayland";
  CLUTTER_BACKEND = "wayland";
  GDK_BACKEND = "wayland";
  MOZ_ENABLE_WAYLAND = "1";

  __GL_GSYNC_ALLOWED = "0";
  __GL_VRR_ALLOWED = "0";
  _JAVA_AWT_WM_NONEREPARENTING = "1";
  SSH_AUTH_SOCK = "/run/user/1000/keyring/ssh";
  DISABLE_QT5_COMPAT = "0";
  DIRENV_LOG_FORMAT = "";
  QT_WAYLAND_DISABLE_WINDOWDECORATION = "1";
}
