#!/usr/bin/env bash
uair-check start
niri msg action focus-workspace task
uairctl jump med-prep
uairzen ': start your day off right by setting intentions 🌅 and aligning with them 🧘' &
sleep 3
niri msg action focus-workspace read
sleep 1
xdg-open "https://coaching.healthygamer.gg/guide/meditation-tracks"
